accounts/urls.py
from django.urls import path
from .views import MyLoginView, MyPasswordChangeView, MySignUpView
from django.contrib.auth.views import LogoutView


app_name = 'accounts'
urlpatterns = [
    path('login/', MyLoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),
    path("password_change/", MyPasswordChangeView.as_view(), name='password_change'),
    path("sign_up/", MySignUpView.as_view(), name='sign_up'),

]

django_site1/urls.py
from django.contrib import admin
from django.urls import path, include
from viewer.views import hello, MoviesView, MoviesViewTemplate,MoviesViewList,MovieCreateView, GenreCreateView , MovieDeleteView

from viewer.views import MovieUpdateView, MovieDeleteView, MovieDetailView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/<s0>/', hello, name="hello"),
    path('', MoviesViewList.as_view(), name="movies"),  # TEmplate Class based view-
    path('movie/create/', MovieCreateView.as_view(), name='movie_create'),
    path('movie/new_genre/', GenreCreateView.as_view(), name='new_genre'),
    path('movie/update/<pk>', MovieUpdateView.as_view(), name='movie_update'),
    path('movie/delete/<pk>', MovieDeleteView.as_view(), name='movie_delete'),
    path('movie/detail/<pk>', MovieDetailView.as_view(), name='movie_detail'),
    path('accounts/',include('accounts.urls', namespace= 'accounts')),
]

viewer/models.py
from django.db.models import DO_NOTHING, CharField, DateField, DateTimeField, ForeignKey, IntegerField,Model, TextField

class Genre(Model):
  name=CharField(max_length=128)


  def __str__(self):
    return self.name

class Movie(Model):
  title = CharField(max_length=128)
  genre = ForeignKey(Genre, on_delete=DO_NOTHING)
  rating = IntegerField()
  released = DateField()
  description = TextField()
  created = DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.title

viewer/forms.py
from django.forms import (
  CharField, DateField, Form, IntegerField, ModelChoiceField, Textarea,ModelForm
)

from datetime import date
from viewer.models import Genre, Movie
import re

  # This is a validator that checks if the value starts with a capital letter
  # If not, it throws an ValidationError Exception
def capitalized_validator(value):
    if value[0].islower():
      raise ValidationError('Value must be capitalized.')

class PastDateField(DateField):
    def validate(self, value):
      super().validate(value)
      if value >= date.today():
        raise ValidationError('Only past dates allowed here.')

    def clean(self, value):
      result = super().clean(value)
      return date(year=result.year, month=result.month, day=1)

# class MovieForm(Form):
#     title = CharField(max_length=128)
#     genre = ModelChoiceField(queryset=Genre.objects)  # To choose a Genre from the model (table) Genre
#     rating = IntegerField(min_value=1, max_value=10)
#     released = PastDateField()
#     description = CharField(widget=Textarea, required=False)
#
#     def clean_description(self):
#         # Force each sentence of the description to be capitalized.
#         initial = self.cleaned_data['description']
#         sentences = re.sub(r'\s*\.\s*', '.', initial).split('.')
#         return '. '.join(sentence.capitalize() for sentence in sentences)
#
#     def clean(self):
#         result = super().clean()
#         if result['genre'].name == 'Comedy' and result['rating'] > 5:
#             self.add_error('genre', 'Comedy Genre')
#             self.add_error('rating', f'Rating:  {result["rating"]}')
#             raise ValidationError(
#                 "Comedies aren't so good to be rated over 5."
#             )
#         return result



class MovieForm(ModelForm):
    class Meta:
        model = Movie
        fields = "__all__"

class GenreForm(ModelForm):
    class Meta:
        model = Genre
        fields = "__all__"

viewer/views.py
from django.shortcuts import render
from .models import Movie
from django.views import View
from django.views.generic import TemplateView, ListView,FormView, CreateView, UpdateView, DeleteView , DetailView
from .forms import MovieForm, GenreForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from logging import getLogger
from django.views.generic import ListView, FormView, CreateView, UpdateView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
LOGGER = getLogger()
from django.http import HttpResponse


# Create your views here.
def hello(request, s0):
    s1 = request.GET.get('s1', '')  # Get the variable s1 from the URL encoder
    return render(
        request, template_name='viewer/hello.html',  # Template is the file you want to load
        context={'adjectives': [s0, s1, 'beautiful', 'wonderful']} # context are the variable you send to the template
    )
# Function view to show movies
def movie_list(request):
    movie_list = Movie.objects.all()
    return render(
        request,
        template_name="viewer/movies.html",
        context={'movies': movie_list}
    )
# Class based view to show movies
class MoviesView(View):
    def get(self, request):
        movie_list = Movie.objects.all()
        return render(
            request,
            template_name="viewer/movies.html",
            context={'movies': movie_list}
        )

# Template View class
class MoviesViewTemplate(TemplateView):
    template_name = "viewer/movies.html"
    extra_context = {'movies': Movie.objects.all()}

class MoviesViewList(ListView):
  template_name = 'viewer/movies.html'
  model = Movie



# class MovieCreateView(FormView):
#     template_name = "viewer/movie_form.html"
#     form_class = MovieForm
#     success_url = reverse_lazy("movies")
#     def form_valid(self, form):
#         result = super().form_valid(form) # Validate the form
#         cleaned_data = form.cleaned_data # Get me the data from the form
#         Movie.objects.create(
#             title=cleaned_data['title'],
#             genre=cleaned_data['genre'],
#             rating=cleaned_data['rating'],
#             released=cleaned_data['released'],
#             description=cleaned_data['description']
#         )
#         return result
#     def form_invalid(self, form):
#         LOGGER.warning('User provided invalid data.')
#         return super().form_invalid(form)

class StaffRequiredMixin(UserPassesTestMixin):
  def test_func(self):
    return self.request.user.is_staff



class MovieListView(ListView):
  template_name = 'movie_list.html'





class MovieCreateView(LoginRequiredMixin, PermissionRequiredMixin, StaffRequiredMixin, CreateView):
    template_name = 'viewer/movie_form.html'
    form_class = MovieForm
    success_url = reverse_lazy("movies")
    permission_required = 'viewer.add_movie'



    def form_invalid(self, form):
        LOGGER.warning('User provided invalid data.')
        return super().form_invalid(form)


class GenreCreateView(CreateView):
    template_name = 'viewer/form.html'
    form_class = GenreForm
    success_url = reverse_lazy("new_genre")


class MovieUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView, StaffRequiredMixin):

  template_name = 'viewer/form.html'
  model = Movie
  form_class = MovieForm
  success_url = reverse_lazy('movies')
  permission_required = 'viewer.change_movie'

  def form_invalid(self, form):
    LOGGER.warning('User provided invalid data while updating a movie.')
    return super().form_invalid(form)

class MovieDeleteView(LoginRequiredMixin, PermissionRequiredMixin, StaffRequiredMixin,  DeleteView):
    template_name = 'viewer/delete_form.html'
    model = Movie
    success_url = reverse_lazy('movies')
    permission_required = 'viewer.delete_movie'


class MovieDetailView(DetailView):
    template_name = 'viewer/movie_detail.html'
    model = Movie
    success_url = reverse_lazy('movies')

viewer/templates/viewer/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HollyMovies</title>
    <!--    CSS BootStrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <!--    JS bootstrap   -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container fixed">
        <a class="navbar-brand" href="/">HollyMovies</a>
        <button
          class="navbar-toggler" type="button"
          data-toggle="collapse" data-target="#navbarNavAltMarkup"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href=" {% url 'movies' %}">
              Home
            </a>
            <a class="nav-item nav-link active" href="{% url 'hello' 'creepy' %}?s1=wonderful">
                Hello
            </a>
          <a class="nav-item nav-link active" href="{% url 'movie_create'  %}">
                New Movie
             </a>
              <a class="nav-item nav-link active" href="{% url 'new_genre'  %}">
                New Genre
             </a>
              <a class="nav-item nav-link active" href="/admin">
                Admin Panel
             </a>
          </div>
        </div>


        <div class="navbar-nav ml-auto">
          <div class="nav-item dropdown">
            {% if user.is_authenticated %}
              <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                {% if user.first_name %}Hello, {{ user.first_name }}!
                {% else %}Hello, {{ user.username }}!{% endif %}
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item text-right" href="{% url 'accounts:logout' %}">Logout</a>
                  <a class="dropdown-item text-right" href="{% url 'accounts:password_change' %}">Change Password</a>

              </div>
            {% else %}
              <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
                You are not logged in.
              </a>
              <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item text-right" href="{% url 'accounts:login' %}">Login</a>
                <a class="dropdown-item text-right" href="{% url 'accounts:sign_up' %}">Sign Up</a>
              </div>
            {% endif %}
          </div>
          </div>


    </div>
</nav>
<div class="container">
  <div class="jumbotron">
    {% block content %}{% endblock %}
  </div>
</div>
</body>
</html>

viewer/templates/viewer/delete_form.html
{% extends "viewer/base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <p>
      Are you sure you want to delete movie "{{ object.title }}" from database?
    </p>
    <input type="submit" value="Submit" class="btn btn-danger">
  </form>
{% endblock %}

viewer/templates/viewer/form.html
{% extends "viewer/base.html" %}

{% block content %}
<form method="post">
       {% csrf_token %}
      <table>{{form}}</table>
      <input type="submit" value="submit" class="btn btn-primary">
</form>
{% endblock %}

viewer/templates/viewer/hello.html
{% extends "viewer/base.html" %}
{% block content %}
<h1>Welcome to HollyMovies!</h1>
    {% for adjective in adjectives %}
      {% if adjective != 'cruel' %}
        <p>This is a {{ adjective }} world...</p>
      {% endif %}
    {% endfor %}
{% endblock %}

viewer/templates/viewer/movie_detail.html
{% extends "viewer/base.html" %}
{% block content %}
<h1>{{ object.title }}</h1>
<h2>{{ object.released }}</h2>
<h3>{{ object.genre}}</h3>
<p><strong>Rating:</strong> {{ object.rating }}</p>
<p>{{ object.description }}</p>
{% endblock %}

viewer/templates/viewer/movie_form.html
{% extends "viewer/base.html" %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <table>{{ form }}</table>
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

viewer/templates/viewer/movies.html
{% extends "viewer/base.html" %}
{% block content %}
  <h1>Welcome to HollyMovies!</h1>
  <ul>
    {% for movie in object_list %}
      <li>

        {{ movie.title }} ({{ movie.released.year }}) - {{ movie.genre.name }}

        <a href="{% url 'movie_detail' movie.id %}">
          View
        </a>
        {% if user.is_authenticated %}
        <a href="{% url 'movie_update' movie.id %}">
          Update
        </a>
        <a href="{% url 'movie_delete' movie.id %}">
          Delete
        </a>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
{% endblock %}